[build]
	publish = 'dist/'
	command = 'npm run build'

[build.environment]
	HUGO_VERSION = '0.72.0'

[build.processing]
	skip_processing = true

[[redirects]]
  from = '/en/*'
	to = '/en/404.html'
  status = 404

[[redirects]]
  from = '/*'
  to = '/404.html'
  status = 404
