[build]
	publish = 'dist/'
	command = 'npm run build'

[build.environment]
	HUGO_VERSION = '0.72.0'
	HUGO_ENV = 'development'

[build.processing]
	skip_processing = true

[context.production.environment]
	HUGO_ENV = 'production'

[context.production.processing]
	skip_processing = true
[context.production.processing.html]
	pretty_urls = false
[context.production.processing.css]
	bundle = false
	minify = false
[context.production.processing.js]
	bundle = false
	minify = false
[build.processing.images]
	compress = true

[[redirects]]
  from = '/en/*'
	to = '/en/404.html'
  status = 404
	force = true

[[redirects]]
  from = '/*'
  to = '/404.html'
  status = 404
	force = true

