[build]
	base = 'site/'
	publish = 'public/'
	command = 'hugo --gc'

[build.environment]
	HUGO_VERSION = '0.66.0'
	HUGO_ENV = 'development'
	HUGO_ENABLEGITINFO = 'true'

[context.production]
	HUGO_ENV = 'production'
	HUGO_ENABLEGITINFO = 'false'
	command = 'hugo --gc --minify'
[context.production.processing]
	skip_processing = false
[context.production.processing.html]
	pretty_urls = false
[build.processing.images]
	compress = true

[[redirects]]
  from = '/*'
  to = '/404.html'
  status = 404
	force = true
  conditions = {Language = ['de']}

[[redirects]]
  from = '/*'
	to = '/en/404.html'
  status = 404
	force = true
