[build]
	base = 'site/'
	publish = 'public/'
	command = 'hugo --gc '

[build.environment]
	HUGO_VERSION = '0.70.0'
	HUGO_ENV = 'development'

[context.production]
	command = 'hugo --gc --minify'

[context.production.environment]
	HUGO_ENV = 'production'

[context.production.processing]
	skip_processing = true
[context.production.processing.html]
	pretty_urls = false
[build.processing.images]
	compress = true

[[redirects]]
  from = '/en/*'
	to = '/en/404.html'
  status = 404
	force = true

[[redirects]]
  from = '/*'
  to = '/404.html'
  status = 404
	force = true

