---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Informationen
- type: document
  path: site/data/events.yaml
  label: Events
- type: document
  path: site/data/music.yaml
  label: Musik
- type: document
  path: site/data/life.yaml
  label: Leben
- type: document
  path: site/data/details.yaml
  label: Details
- type: heading
  label: Seiten
- type: directory
  path: site/content
  label: Deutsche Seiten
  create: all
  match: "**/*.de.md"
  new_doc_ext: de.md
- type: directory
  path: site/content
  label: Englische Seiten
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
upload_dir: static/---none---
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: dist
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start -- --minify
version: 0.71.1
