defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
uglyURLs = false
disableKinds = ['taxonomy', 'taxonomyTerm', 'RSS']

title = 'Niklas A. Chroust'
baseURL = 'https://niklaschroust.com/'
googleAnalytics = 'UA-170179785-1'

[params]
	author = 'Niklas A. Chroust'
	firstname = 'Niklas'
	middlename = 'Alexander'
	surname = 'Chroust'

	[params.details]
		picturesContact = 'Ella Chroust'
		webdesignContact = 'Adrian Chroust'

		sourceCode = 'Github'
		sourceCodeURL = 'https://github.com/adrnc/niklaschroust'

		host = 'Netlify'
		hostURL = 'https://www.netlify.com/'

		contentManagement = 'Forestry'
		contentManagementURL = 'https://forestry.io/'

[languages]
	[languages.de]
		weight = 1
		languageName = 'Deutsch'
		languageCode = 'de'
		[languages.de.params]
			keywords = ['chroust', 'niklas chroust', 'musik', 'komposition']
			description = 'Persönliche Website von Niklas A. Chroust'
	[languages.en]
		weight = 2
		languageName = 'English'
		languageCode = 'en'
		[languages.en.params]
			keywords = ['chroust', 'niklas chroust', 'music', 'composition']
			description = 'Personal website of Niklas A. Chroust'

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		respectDoNotTrack = true
		useSessionStorage = true
	[privacy.twitter]
		enableDNT = true
	[privacy.youtube]
		privacyEnhanced = true

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			autoHeadingIDType = 'blackfriday'
