defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
uglyURLs = false
disableKinds = ['taxonomy', 'taxonomyTerm', 'RSS']

title = 'Niklas A. Chroust'
baseURL = 'https://niklaschroust.com/'
googleAnalytics = 'UA-170179785-1'

[params]
	author = 'Niklas A. Chroust'
	firstname = 'Niklas'
	middlename = 'Alexander'
	surname = 'Chroust'

[languages]
	[languages.de]
		weight = 1
		languageName = 'Deutsch'
		languageCode = 'de'
		[languages.de.params]
			keywords = ['chroust', 'niklas chroust', 'musik', 'komposition']
			description = 'Persönliche Website von Niklas A. Chroust'
	[languages.en]
		weight = 2
		languageName = 'English'
		languageCode = 'en'
		[languages.en.params]
			keywords = ['chroust', 'niklas chroust', 'music', 'composition']
			description = 'Personal website of Niklas A. Chroust'

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		respectDoNotTrack = true
		useSessionStorage = true
	[privacy.twitter]
		enableDNT = true
	[privacy.youtube]
		privacyEnhanced = true

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			autoHeadingIDType = 'blackfriday'

[menu]
  [[menu.main]]
    identifier = 'home'
		image = '/background-images/default.jpg'
  [[menu.main]]
    identifier = 'events'
		image = '/background-images/events.jpg'
  [[menu.main]]
    identifier = 'press'
		image = '/background-images/press.jpg'
  [[menu.main]]
    identifier = 'music'
		image = '/background-images/music.jpg'
  [[menu.main]]
    identifier = 'biography'
		image = '/background-images/biography.jpg'
  [[menu.main]]
    identifier = 'gallery'
		image = '/background-images/gallery.jpg'
  [[menu.main]]
    identifier = 'contact'
		image = '/background-images/contact.jpg'
